---
title: 'Lab 4: Three Views of Projectile Ball'
author: "Shovit Bhari"
date: "6/5/2020"
output:
  html_document:
    df_print: paged
---

```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab 4: Three Views of Projectile Ball
```{r , echo=FALSE}

t <- seq(0,1.1, by=0.1)
x<- c(0.0, 0.7,1.35,2.0,2.65,3.3,4,4.65,5.3,5.95,6.5,NA)
vx <- c(NA, 6.75, 6.5, 6.5, 6.5, 1, 6.75, 6.75, 6.5, 6.5, 6, NA)
y <- c(1,1.5,1.9,2.15,2.3,2.4,2.3,2.15,1.9,1.6,1.2,0.7)
vy<- c(NA, 4.5, 3.25, 2, 1.25, 0, -1.25, -2, -2.75, -3.5, -4.5, NA)
```
## Data
```{r , echo=FALSE}
data <- data.frame(t,x,vx,y,vy)
data
```

```{r}
xt <- lm(x~t, data)
plot(t,x, xlab="Time", ylab="Horizontal Position", main = "Horizontal Displacement")
abline(xt)
```

```{r}
summary(xt)$coef
```

```{r , echo=FALSE}
slope1 <- round(summary(xt)$coef[2,1],3)
intercept1<- round(summary(xt)$coef[1,1],3)
ei1 <- round(summary(xt)$coef[1,2],3)
es1 <- round(summary(xt)$coef[2,2],3)
```

$$ v_x = `r slope1` \pm `r es1` \frac{m}{s} $$

```{r}
vt <- lm(vx~t, data)
plot(t,vx, xlab="Time", ylab="Horizontal Velocity", main = "Horizontal Velocity")
abline(vt)
```

```{r}
summary(vt)$coef
```

```{r , echo=FALSE}
slope2 <- round(summary(vt)$coef[2,1],3)
intercept2<- round(summary(vt)$coef[1,1],3)
ei2 <- round(summary(vt)$coef[1,2],3)
es2 <- round(summary(vt)$coef[2,2],3)
```

$$ a = `r slope2` \pm `r es2` \frac{m}{s^2} $$

```{r}
plot(t,y, xlab="Time", ylab="Vertical Position", main = "Vertical Displacement")
```

```{r}
vyt <- lm(vy~t, data)
plot(t,vy, xlab="Time", ylab="Vertical Velocity", main = "Vertical Velocity")
abline(vyt)
```

```{r}
summary(vyt)$coef
```

```{r , echo=FALSE}
slope3 <- round(summary(vyt)$coef[2,1],3)
intercept3<- round(summary(vyt)$coef[1,1],3)
ei3 <- round(summary(vyt)$coef[1,2],3)
es3 <- round(summary(vyt)$coef[2,2],3)
```

$$ v_o = `r intercept3` \pm `r ei3` \frac{m}{s} $$

$$ g = `r slope3` \pm `r es3` \frac{m}{s^2} $$
