# Lab 6: Simple Harmonic Motion

## Spring Constant

```{r , echo=FALSE,message=FALSE,warning=FALSE}
library(plotly)
#Mass in grams
Mass<- c(0,100,200,300,400)
#displacement in cm
disp <- c(6.9, 5.9, 4.7, 3.7, 2.7)
#displacement in m
Position <- disp/100
#Force Gravity in Newtons
Fg<- (Mass/1000)*9.81

```
## Data Set
```{r, echo=FALSE, message=FALSE, warning=FALSE, comment=" "}
data <- data.frame(Mass, disp,Position, Fg)
data
```

Coefficients 
```{r ,echo=FALSE,warning=FALSE, comment=" "}
fit<- lm(Fg~Position, data)
summary(fit)$coef
```

```{r ,echo=FALSE,warning=FALSE, message=FALSE, comment=" "}

slope1 <- round(summary(fit)$coef[2,1],3)
intercept1<- round(summary(fit)$coef[1,1],3)
ei1 <- round(summary(fit)$coef[1,2],3)
es1 <- round(summary(fit)$coef[2,2],3)
```
## Plot
```{r ,echo=FALSE, warning=FALSE, message=FALSE}
x1 <- ggplot(data, aes(Position, Fg)) +
         geom_smooth(method='lm', se=TRUE) + 
         geom_point(col="red") +
         theme(plot.title = element_text(hjust=0.5)) +
         labs(title = "Force on a spring", x="Position", y = "Force")+
         theme(plot.title = element_text(color="blue", size=14, face="bold"))

fig1 <- ggplotly(x1)
fig1
```

## Results
$$  k = \mid `r slope1` \pm `r es1` \mid $$

## Spring Oscillator on an Air Track




```{r , echo=FALSE,message=FALSE,warning=FALSE}

#Mass in grams
Mass<- c(0.133, 0.233,0.333, 0.433, 0.533,0.633 )
#time for 4 oscillations
t4 <- c(0.99, 1.29, 1.50833, 1.729, 1.904, 2.083)
T <- t4/4
Tsq <- T^2


```
## Data Set
```{r, echo=FALSE, message=FALSE, warning=FALSE, comment=" "}
data <- data.frame(Mass,t4, T, Tsq)
data
```

Coefficients 
```{r ,echo=FALSE,warning=FALSE, comment=" "}
fit<- lm(Tsq~Mass, data)
summary(fit)$coef
```

```{r ,echo=FALSE,warning=FALSE, message=FALSE, comment=" "}

slope1 <- round(summary(fit)$coef[2,1],3)
intercept1<- round(summary(fit)$coef[1,1],3)
ei1 <- round(summary(fit)$coef[1,2],3)
es1 <- round(summary(fit)$coef[2,2],3)
```
## Plot
```{r ,echo=FALSE, warning=FALSE, message=FALSE}
x1 <- ggplot(data, aes(Mass, Tsq)) +
         geom_smooth(method='lm', se=TRUE) + 
         geom_point(col="red") +
         theme(plot.title = element_text(hjust=0.5)) +
         labs(title = "Force on a spring", x="Mass", y = "Time Period Squared")+
         theme(plot.title = element_text(color="blue", size=14, face="bold"))

fig1 <- ggplotly(x1)
fig1
```

## Results
$$  slope = \mid `r slope1` \pm `r es1` \mid $$
