---
title: 'Lab8: Conservation of Energy'
output:
  pdf_document: default
  html_document: default
date: "6/17/2020"
---

```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

```{r,echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(plotly)
```
# Lab 8: Conservation of Energy

```{r, echo=FALSE, warning=FALSE, message=FALSE}
tA<- c(0,0.025,0.05,0.075,0.1,0.125)
xA<- c(0,0.01,0.025,0.035,0.045,0.06)
tC<- c(0,0.025,0.05,0.075,0.1,0.125)
xC <- c(0,0.025,0.05,0.075,0.1,0.125)
tH<- c(0,0.0125,0.025,0.0375,0.05,0.0625)
xH <- c(0,0.025,0.048,0.07,0.095,0.12)
tI<- c(0,0.0125,0.025,0.0375,0.05,0.0625)
xI <- c(0,0.026,0.05,0.075,0.1,0.128)
tK<- c(0,0.0125,0.025,0.0375,0.05,0.0625)
xK <- c(0,0.03,0.06,0.09,0.115,0.145)
```

```{r}
data <- data.frame(tA,xA, tC, xC, tH, xH, tI, xI, tK, xK)
```

```{r fits,echo=FALSE,warning=FALSE, comment=" "}
fitA<- lm(xA~tA, data)
fitC<- lm(xC~tC, data)
fitH<- lm(xH~tH, data)
fitI<- lm(xI~tI, data)
fitK<- lm(xK~tK, data)
```

```{r ,echo=FALSE,warning=FALSE, message=FALSE, comment=" "}
slopeA <- round(summary(fitA)$coef[2,1],3)
interceptA<- round(summary(fitA)$coef[1,1],3)
eiA <- round(summary(fitA)$coef[1,2],3)
esA <- round(summary(fitA)$coef[2,2],3)
```

```{r ,echo=FALSE,warning=FALSE, message=FALSE, comment=" "}
slopeC <- round(summary(fitC)$coef[2,1],3)
interceptC<- round(summary(fitC)$coef[1,1],3)
eiC<- round(summary(fitC)$coef[1,2],3)
esC <- round(summary(fitC)$coef[2,2],3)
```

```{r ,echo=FALSE,warning=FALSE, message=FALSE, comment=" "}
slopeH<- round(summary(fitH)$coef[2,1],3)
interceptH<- round(summary(fitH)$coef[1,1],3)
eiH <- round(summary(fitH)$coef[1,2],3)
esH <- round(summary(fitH)$coef[2,2],3)
```

```{r ,echo=FALSE,warning=FALSE, message=FALSE, comment=" "}
slopeI <- round(summary(fitI)$coef[2,1],3)
interceptI<- round(summary(fitI)$coef[1,1],3)
eiI <- round(summary(fitI)$coef[1,2],3)
esI <- round(summary(fitI)$coef[2,2],3)
```

```{r ,echo=FALSE,warning=FALSE, message=FALSE, comment=" "}
slopeK <- round(summary(fitK)$coef[2,1],3)
interceptK<- round(summary(fitK)$coef[1,1],3)
eiK <- round(summary(fitK)$coef[1,2],3)
esK <- round(summary(fitK)$coef[2,2],3)
```

```{r , echo=FALSE,warning=FALSE, message=FALSE, comment=" "}
height <- c(0.03, 0.085, 0.205, 0.235, 0.29)
velocity <- c(slopeA, slopeC, slopeH, slopeI, slopeK)
velocitysq <- velocity^2
```

```{r , echo=FALSE, comment=" "}
datav <- data.frame(height, velocity, velocitysq)
datav
```

```{r fitv, echo=FALSE, comment=" "}
fitv <- lm(velocitysq~height)
```

```{r ,echo=FALSE,warning=FALSE, message=FALSE, comment=" "}
slope <- round(summary(fitv)$coef[2,1],3)
intercept<- round(summary(fitv)$coef[1,1],3)
ei <- round(summary(fitv)$coef[1,2],3)
es <- round(summary(fitv)$coef[2,2],3)
gra <- slope/2
eg <- es/2
```

```{r}
g <- ggplot(data=datav, aes(x=height, y=velocitysq)) +
        geom_point(col="red") +
        geom_smooth(method='lm', se=TRUE) + 
        theme(plot.title = element_text(hjust=0.5)) +
        labs(title = "Velocity Squared vs Height", x="Height", y = "Velocity Squared")+
        theme(plot.title = element_text(color="blue", size=14, face="bold"))
p <- ggplotly(g)
p
```

$$g = `r gra` \pm `r eg`$$