---
title: "Lab9: Ballistic Pendulum"
date: "`r Sys.Date()`"
output: html_document
---

```{r , include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
```

# Lab 9: Ballistic Pendulum

```{r,echo=FALSE, message=FALSE, warning=FALSE}
library(ggplot2)
library(dplyr)
library(plotly)
```


```{r, echo=FALSE, eval=TRUE, warning=FALSE, message=FALSE}
time <- c(0,0.00125, 0.0025, 0.00375, 0.005, 0.00625)
position <- c(0,0.1,0.19,0.31,0.41, 0.51)

```

### Data
```{r ,echo=TRUE,warning=FALSE, message=FALSE, comment=" "}
data <- data.frame(time, position)
data
```

```{r}
fit<- lm(position~time, data)
```

```{r ,echo=TRUE,warning=FALSE, message=FALSE, comment=" "}

slope <- round(summary(fit)$coef[2,1],3)
intercept<- round(summary(fit)$coef[1,1],3)
ei <- round(summary(fit)$coef[1,2],3)
es <- round(summary(fit)$coef[2,2],3)
```

```{r , message=FALSE, warning=FALSE}
g <- ggplot(data=data, aes(x=time, y=position)) +
        geom_point(col="red") +
        geom_smooth(method='lm', se=TRUE) + 
        theme(plot.title = element_text(hjust=0.5)) +
        labs(title = "Position vs Time", x="Time", y = "Position")+
        theme(plot.title = element_text(color="blue", size=14, face="bold"))
p <- ggplotly(g)
p
```

$$ v_o = `r slope` \pm `r es` \frac{m}{s} $$ 